substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "hello-repo"
  _SERVICE_PREFIX: "hello-world"

options:
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_PREFIX}:${SHORT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_PREFIX}:${SHORT_SHA}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Set SERVICE_NAME'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "SERVICE_NAME=${_SERVICE_PREFIX}-dev" >> $$_ENV_FILE
        elif [[ "$BRANCH_NAME" == "staging" ]]; then
          echo "SERVICE_NAME=${_SERVICE_PREFIX}-staging" >> $$_ENV_FILE
        else
          echo "SERVICE_NAME=${_SERVICE_PREFIX}-prod" >> $$_ENV_FILE
        fi
    env:
      - '_ENV_FILE=/workspace/build_env'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/build_env
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_PREFIX}:${SHORT_SHA}"
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          gcloud run deploy "$SERVICE_NAME" \
            --image="$IMAGE" \
            --region="${_REGION}" \
            --platform=managed \
            --allow-unauthenticated
        else
          gcloud run deploy "$SERVICE_NAME" \
            --image="$IMAGE" \
            --region="${_REGION}" \
            --platform=managed \
            --no-traffic \
            --allow-unauthenticated
        fi

  - id: 'Approval for traffic switch'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "Dev branch - skipping approval."
        else
          echo "Awaiting manual approval to switch traffic..."
        fi
    approval: true

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Switch traffic to 100%'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "Dev branch - traffic already switched."
          exit 0
        fi
        source /workspace/build_env
        REV=$(gcloud run revisions list --service="$SERVICE_NAME" --region="${_REGION}" --format='value(metadata.name)' --limit=1)
        gcloud run services update-traffic "$SERVICE_NAME" \
          --region="${_REGION}" \
          --to-revisions "${REV}=100"

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_PREFIX}:${SHORT_SHA}'
